### PR TITLE
build static webpage with Docsify

### PR DESCRIPTION
**Pull request by AdvancedWipe**
Build webpage with docsify, see here https://docsify.js.org/.
I rebuild the website that is being depoyed on Github pages, to use docsify. All content is copied from the existing webpage, with minor changes.

Edit: added link

### CODE REVIEW

**Comment by AdvancedWipe** [comment]
There is more potential to use docsify. Markdown pages can be simply added to be displayed on the webpage, my thought was that if a changelog file will be created at the main repo it can be embedded to the website easily to replace the changes below the downloads or to have a separate changelog that contains all changes ever made.... Hope that is useful!

**Comment by Brandonbr1** [comment]
> Build webpage with docsify, see here https://docsify.js.org/. I rebuild the website that is being depoyed on Github pages, to use docsify. All content is copied from the existing webpage, with minor changes.
> 
> Edit: added link

Ahh no

the thing is that  Hugo and Jelly would be better 

science https://docsify.js.org/. is meant for docs and not a full website like Ca
it gives you way more control

**Comment by AdvancedWipe** [comment]
Ah yes, haven't heard of it yet. But that looks way better... Is there a plan to start to deploy the website with hugo or jelly?

**Comment by Brandonbr1** [comment]
> Ah yes, haven't heard of it yet. But that looks way better... Is there a plan to start to deploy the website with hugo or jelly?

Well the website as it is does it job perfect fine it doesn't need to be changed 

IDK if there is any plan to change because I don't work at CA

**Pull request closed without merging**
